node {
    stage('git clone') {
        git 'https://github.com/anhyeokkyun/anhyeokkyun.github.io'
    }
    stage('Test') {
        echo 'Testing...'
    }
    stage('execute sh') {
		sh "chmod 774 ./aws/ec2/jenkins/project_test02-git_pipeline.sh"
        sh "./aws/ec2/jenkins/project_test02-git_pipeline.sh"
    }
}
