pipeline {
    agent any
    
    stages() {
        stage('git clone') {
            steps() {
                git 'https://github.com/anhyeokkyun/anhyeokkyun.github.io'
            }
        }
        
        stage('Test') {
            steps {
                echo 'Testing...'
            }
        }
        
        stage('execute sh') {
            steps {
                sh "chmod 774 ./aws/ec2/jenkins/project_test02-git_pipeline.sh"
                sh "./aws/ec2/jenkins/project_test02-git_pipeline.sh
            }
        }        
    }
}
