pipeline {
    agent any
    
    stages() {
        stage('git clone') {
            steps() {
                git 'https://github.com/anhyeokkyun/anhyeokkyun.github.io'
            }
        }
        
        stage('Test') {
            steps {
                echo 'Testing...'
            }
        }
        
        stage('Deploy') {
            steps {
		sshagent(credentials: ['jenkins-key']) {
		    sh '''
			ssh -o StrictHostKeyChecking=no root@172.21.2.171 uptime
			scp /git/aws/ec2/jenkins/project_test02-git_pipeline.sh root@172.21.2.171:/root/

			ssh -t root@172.21.2.171 ./project_test02-git_pipeline.sh
		    '''
		}
            }
        }        
    }
}
