echo "This is a test for Jenkins pipeline with github."
echo "This is the second message of pipeline change."
echo "This is the third message of pipeline change."
echo "This is the fourth message of pipeline change."
echo "This is the fifth message of pipeline change."
